# Generated by Django 4.2.20 on 2025-03-20 11:10

from django.db import migrations


def remove_test_model_default_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias

    try:
        test_model_content_type = ContentType.objects.using(db_alias).get(app_label="db", model="testmodel")
        Permission.objects.using(db_alias).filter(content_type=test_model_content_type).delete()
    except ContentType.DoesNotExist:
        return


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testmodel",
            options={"default_permissions": ()},
        ),
        migrations.RunPython(
            code=remove_test_model_default_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
